<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>org.eclipse.datagrid</groupId>
		<artifactId>cluster-nodelibrary-parent</artifactId>
		<version>1.0.0-SNAPSHOT</version>
		<relativePath>../pom.xml</relativePath>
	</parent>

	<artifactId>cluster-nodelibrary-micronaut</artifactId>

	<name>Eclipse Data Grid Cluster Nodelibrary Micronaut</name>
	<description>Eclipse Data Grid Cluster Nodelibrary Micronaut Implementation</description>
	<url>https://projects.eclipse.org/projects/technology.datagrid</url>

	<properties>
		<packaging>jar</packaging>
		<maven.compiler.parameters>true</maven.compiler.parameters>
		<micronaut.version>4.9.2</micronaut.version>
		<micronaut.eclipsestore.version>1.10.0</micronaut.eclipsestore.version>
		<micronaut.serialization.version>2.15.1</micronaut.serialization.version>
	</properties>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>io.micronaut.platform</groupId>
				<artifactId>micronaut-parent</artifactId>
				<version>${micronaut.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<dependencies>
		<dependency>
			<groupId>org.eclipse.datagrid</groupId>
			<artifactId>cluster-nodelibrary</artifactId>
			<version>1.0.0-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>io.micronaut</groupId>
			<artifactId>micronaut-inject</artifactId>
		</dependency>
		<dependency>
			<groupId>jakarta.annotation</groupId>
			<artifactId>jakarta.annotation-api</artifactId>
		</dependency>
		<dependency>
			<groupId>io.micronaut</groupId>
			<artifactId>micronaut-http-server-netty</artifactId>
		</dependency>
		<dependency>
			<groupId>io.micronaut.serde</groupId>
			<artifactId>micronaut-serde-jackson</artifactId>
		</dependency>
		<dependency>
			<groupId>io.micronaut.eclipsestore</groupId>
			<artifactId>micronaut-eclipsestore</artifactId>
		</dependency>
		<dependency>
			<groupId>io.micronaut.eclipsestore</groupId>
			<artifactId>micronaut-eclipsestore-annotations</artifactId>
		</dependency>
		<dependency>
			<groupId>commons-io</groupId>
			<artifactId>commons-io</artifactId>
		</dependency>
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-compress</artifactId>
		</dependency>
		<dependency>
			<groupId>org.eclipse.store</groupId>
			<artifactId>storage-embedded</artifactId>
			<version>${eclipse-store.version}</version>
		</dependency>
		<dependency>
			<groupId>org.eclipse.store</groupId>
			<artifactId>storage-embedded-configuration</artifactId>
			<version>${eclipse-store.version}</version>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<configuration combine.self="override">
					<annotationProcessorPaths>
						<path>
							<groupId>io.micronaut</groupId>
							<artifactId>micronaut-inject-java</artifactId>
							<version>${micronaut.version}</version>
						</path>
						<path>
							<groupId>io.micronaut</groupId>
							<artifactId>micronaut-http-validation</artifactId>
							<version>${micronaut.version}</version>
						</path>
						<path>
							<groupId>io.micronaut.eclipsestore</groupId>
							<artifactId>micronaut-eclipsestore-annotations</artifactId>
							<version>${micronaut.eclipsestore.version}</version>
							<exclusions>
								<exclusion>
									<groupId>io.micronaut</groupId>
									<artifactId>micronaut-inject</artifactId>
								</exclusion>
							</exclusions>
						</path>
						<path>
							<groupId>io.micronaut.serde</groupId>
							<artifactId>micronaut-serde-processor</artifactId>
							<version>${micronaut.serialization.version}</version>
							<exclusions>
								<exclusion>
									<groupId>io.micronaut</groupId>
									<artifactId>micronaut-inject</artifactId>
								</exclusion>
							</exclusions>
						</path>
					</annotationProcessorPaths>
				</configuration>
				<executions>
					<execution>
						<id>default-compile</id>
						<configuration>
							<compilerArgument combine.self="override"></compilerArgument>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>

</project>
