package peruncs.cluster.storage.aeron.crashtest;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

/// Unit coverage for the shared forked-cell payload generator: parent and
/// child must agree byte-for-byte, so determinism and bounds are asserted
/// here instead of debugged across process boundaries.
class CrashPayloadsTest {
    /// Verifies the default payload preserves the historical 64-byte digest cells.
    @Test
    void historicalDefaultIs64DigestBytes() {
        final byte[] payload = CrashPayloads.sized(1, 64, "digest");
        assertEquals(64, payload.length);
        assertArrayEquals(CrashPayloads.sized(1, 64, "digest"), payload);
    }

    /// Verifies sequence and kind both change the generated bytes.
    @Test
    void sequencesDifferKindsDiffer() {
        assertFalse(java.util.Arrays.equals(
                CrashPayloads.sized(0, 64, "digest"), CrashPayloads.sized(1, 64, "digest")));
        assertFalse(java.util.Arrays.equals(
                CrashPayloads.sized(1, 4096, "digest"), CrashPayloads.sized(1, 4096, "random")));
    }

    /// Verifies every envelope/chunk/MTU boundary size comes out exact.
    @Test
    void boundarySizesAreExact() {
        for (final int size : new int[]{1, 1023, 1025, 16383, 16384, 16385, 65536, 200_000}) {
            assertEquals(size, CrashPayloads.sized(0, size, "digest").length, "size=%d".formatted(size));
            assertEquals(size, CrashPayloads.sized(0, size, "random").length, "size=%d".formatted(size));
        }
    }

    /// Verifies empty, oversized, and unknown-kind payloads are rejected fast.
    @Test
    void rejectsOutOfRangeSizesAndKinds() {
        assertThrows(IllegalArgumentException.class, () -> CrashPayloads.sized(0, 0, "digest"));
        assertThrows(IllegalArgumentException.class,
                () -> CrashPayloads.sized(0, CrashPayloads.MAX_SIZE + 1, "digest"));
        assertThrows(IllegalArgumentException.class, () -> CrashPayloads.sized(0, 64, "text"));
    }
}
