<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.eclipse.datagrid</groupId>
        <artifactId>cache-parent</artifactId>
        <version>1.0.0-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>cache-clustered-parent</artifactId>
    <packaging>pom</packaging>

    <name>Eclipse Data Grid Cache Clustered Parent</name>
    <description>Eclipse Data Grid Cache Clustered Project</description>
    <url>https://projects.eclipse.org/projects/technology.datagrid</url>

    <modules>
        <module>clustered</module>
        <module>kafka</module>
        <module>aeron</module>
    </modules>

    <dependencyManagement>
        <dependencies>
        </dependencies>
    </dependencyManagement>

</project>
